### ISSUE TITLE
Docker builds fail silently due to lack of libsystemd-dev

### ISSUE THREAD

**Issue by lolPants** [Glimesh/janus-ftl-plugin#103]
As noted in the title, the Dockerfile was not modified in #99 to add `libsystemd-dev`, presumably due to Docker images not benefiting from using systemd. However because of this, the build silently fails as Meson notes the missing dependency and does not build the project. After reading over #99 I believe this to be an error due to misconfiguration of Meson, as it seems that compile time support was meant to be optional.

**Comment by danstiner** [comment]
Hmm systemd support was indeed meant to be optional, I'll look at how it broke

**Comment by danstiner** [comment]
@lolPants could you share the output you see? I'm having trouble reproducing

**Comment by lolPants** [comment]
This is the full Docker build log, the relevant Janus FTL build step starts at line 2627. The rest of the logfile is installing dependencies and such, but is included for completeness sake. This build was performed against c8666a63e043cbea91734092a2d50ac6400727ff (latest master at time of writing).

https://pastebin.com/EPb40Zga

**Comment by lolPants** [comment]
As a follow-up, simply adding `libsystem-dev` to the Dockerfile results in the build completing as expected.
https://pastebin.com/wcrUxFbS (line 2647)

**Comment by danstiner** [comment]
Thanks, PR out with the fix.
(I'm having issues with Docker on WSL2 so it was hard for me to repro, sharing the output helped)
