### ISSUE TITLE
Access token request failed during janus startup connecting to Glimesh app

### ISSUE THREAD

**Issue by 4563453** [Glimesh/janus-ftl-plugin#137]
Hello, trying to setup glimesh app and janus server I have a runnung glimesh, configured and running waiting for incoming ftl stream. 
My Janus, just build from github fails during connect to glimesh.

FTL_SERVICE_CONNECTION, FTL_SERVICE_GLIMESH_HOSTNAME, FTL_SERVICE_GLIMESH_PORT, FTL_SERVICE_GLIMESH_HTTPS, FTL_SERVICE_GLIMESH_CLIENTID, FTL_SERVICE_GLIMESH_CLIENTSECRET
are configured in docker-compose environment. 

Error messages during boot: 

janus-ftl-deployed | [Tue May 31 20:26:11 2022] Event handlers support disabled
janus-ftl-deployed | [Tue May 31 20:26:11 2022] Plugins folder: /opt/janus/lib/janus/plugins
janus-ftl-deployed | [Tue May 31 20:26:11 2022] Loading plugin 'libjanus_ftl.so'...
janus-ftl-deployed | [Tue May 31 20:26:11 2022] Joining Janus requests handler thread
janus-ftl-deployed | [Tue May 31 20:26:11 2022] Sessions watchdog started
janus-ftl-deployed | [2022-05-31 20:26:11.601] [info] Using Glimesh Service Connection @ https://x.24.3.14:4001
janus-ftl-deployed | [Tue May 31 20:26:11 2022] Janus FTL Plugin created!
janus-ftl-deployed | terminate called after throwing an instance of 'std::runtime_error'
janus-ftl-deployed |   what():  Access token request failed!

I checked CLIENTID and CLIENTSECRET using Insomnia. Api Login works fine.

**Comment by danstiner** [comment]
My first guess is this is something to do with https, possibly the the certificate you are using for glimesh web is not trusted by the Janus server? Setting up https can be tricky, I often don't for local testing.

Unfortunately it looks like we don't have much useful logging for what exactly is going wrong. Swear I'd added some but I guess not. Should be easy to add if you want to send a PR! Line https://github.com/Glimesh/janus-ftl-plugin/blob/7d49f9edae8c47e1feccbe9472a2b07bc3afd783/src/ServiceConnections/GlimeshServiceConnection.cpp#L295 is generating the error

**Comment by 4563453** [comment]
I confirm an issue with certificate, its fixed and system is working now. Yes the logging could be better.
