### ISSUE TITLE
Generate thumbnails from keyframes

### ISSUE THREAD

**Issue by haydenmc** [Glimesh/janus-ftl-plugin#16]
We'll want to generate thumbnails so that services using the FTL plugin can show previews of each stream.

This task will involve decoding the h264 iframe (probably using libav or something), re-encoding as some kind of compressed bitmap (png, jpg) and handing it to the `ServiceConnection`.

**Comment by clone1018** [comment]
Done @haydenmc ?

**Comment by haydenmc** [comment]
Yessiree!
