### ISSUE TITLE
Intermittent crashes when restarting a stream immediately after stopping it

### ISSUE THREAD

**Issue by danstiner** [Glimesh/janus-ftl-plugin#38]
To reproduce, open OBS and spam the start/stop streaming button until the janus server terminates.

Per the title, This seems to specifically be from starting a FTL stream again immediately after stopping it. The server will terminate and print the following output:
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Attempt to add FTL Stream with a channel ID that is already assigned.
```

This seems to be from a reasonable exception that should just be caught further up the stack instead of terminating the entire server: https://github.com/Glimesh/janus-ftl-plugin/blob/8b898956ba160ddd83a030f6c8eea809b7b21780/FtlStreamStore.cpp#L28-L32

Discovered while testing file descriptor leaks (#18) by starting and stopping streaming in OBS a bunch.

**Comment by haydenmc** [comment]
Good bug!

Yeah, I think the ideal behavior would be to either terminate the new connection, or terminate the existing one. I lean toward the latter, as I imagine the common case is OBS trying to reconnect before the old connection has finished timing out.

**Comment by haydenmc** [comment]
#60 will now terminate existing connections on the same channel if a new stream starts.
