### ISSUE TITLE
Create a generic, configurable RestServiceConnection to communicate with simple RESTful services

### ISSUE THREAD

**Issue by lolPants** [Glimesh/janus-ftl-plugin#71]
Currently while using the dummy service, the HMAC portion of the stream key is fixed. I request some way of allowing this to be based off the channel ID, using a server-known secret key. For a user to stream to an ingest server under this mode they would have to be given a pre-generated HMAC key by a server operator.

## Use Case
Currently using the `FTL_SERVICE_DUMMY_HMAC_KEY` a server can be secured from anyone being able to stream. However anyone who knows the HMAC key can use any channel ID they choose, which might not be ideal for all setups. Under this proposed system they would only be able to use the stream key they are given, which is only valid for a single channel ID.

**Comment by danstiner** [comment]
Hey Jack,

I'm just a fellow contributor so I don't speak in any official capacity but I can share some context.

This plugin is being developed in the open primarily to support a new streaming platform (https://glimesh.tv/about). I added the ability to set `FTL_SERVICE_DUMMY_HMAC_KEY` purely as a way to enable testing a local instance of the plugin, it is not meant for production use. Normally this plugin is run as part of a whole backend infrastructure for Glimesh, and in that case we will securely generate a unique stream key for each user and do all kinds of other orchestration to make streaming scale to hundreds (or hopefully someday thousands!) of viewers.

I see you are working on a web server instance yourself (https://github.com/nerdcubed/ftl). If you are interested in working on low-latency streaming I'd encourage you to consider joining the Glimesh community ([Discord #dev channel](https://discord.gg/glimesh)), we always welcome new contributors.

**Comment by lolPants** [comment]
That all makes sense. For a little context on my specific use case: we've been looking into some way of aggregating multiple POVs for a livestream with minimal latency, so some way of ingesting a small amount of video feeds and restreaming them is required. Previously we've looked into RTMP and SRT, but both of them have their problems. FTL has proved to be the best solution and this Janus plugin has served well in testing. However, when scaling up to allow external parties to stream their POVs (for example, a video game tournament) we would like some way of ensuring said external parties are only authorized to stream under a single channel ID.

The project at https://github.com/nerdcubed/ftl is currently just a specialised FTL web player designed for use inside OBS. For our use case a full deployment of Glimesh proved to be overkill, hence this feature request. I'd be happy to attempt to implement my request myself, but my working knowledge of C++ is fairly limited so I thought I'd propose it for anyone with more experience to potentially look at.

**Comment by haydenmc** [comment]
Thanks Dan, and hi Jack!

To build on Dan's advice there, if you're wanting to hook up janus-ftl-plugin to your server to receive dynamic hmac keys for each channel ID, the intended way to achieve that is to implement a [`ServiceConnection`](https://github.com/Glimesh/janus-ftl-plugin/blob/master/src/ServiceConnections/ServiceConnection.h), which is an abstraction allowing Janus to retrieve and report information from an external service (`GetHmacKey(...)`, `StartStream(...)`, `UpdateStreamMetadata(...)`, `SendJpegPreviewImage(...)`, etc.)

It might make sense to add a more generic ServiceConnection implementation that can use a configurable set of REST endpoints so folks can easily plug this into whatever service infra they're cooking up without having to write their own ServiceConnection.

Mind if I rename this issue to track that task?

**Comment by lolPants** [comment]
I was thinking about something like what you described originally, but wanted to limit the scope for simplicity in case I was to implement it myself. A generic REST system makes much more sense though, so feel free to rename 😄

**Comment by haydenmc** [comment]
@danstiner one thing we might also consider separately is enabling some simple syntax for configuring channelID+streamkey pairs for DummyServiceConnection, so folks could distribute a set of preconfigured stream keys to a small set of users.
