### ISSUE TITLE
Potential deadlock introduced by #72

### ISSUE THREAD

**Issue by lolPants** [Glimesh/janus-ftl-plugin#74]
After testing the new REST service using the latest master, which introduces new code from #72 (which wasn't around while writing the REST service), when a stream fails to authenticate the server seems to lock up. No new connections can be made, no attempt to contact the REST API is made, and when trying to exit with a <kbd>CTRL+C</kbd> the process hangs. (You can still spam <kbd>CTRL+C</kbd> to exit, but Janus warns about freeing resources cleanly)

This behaviour was not noted during development of #73 so I can only attribute it to #72

**Comment by haydenmc** [comment]
Will take a look, thanks!
