### ISSUE TITLE
Fix NACKs to more gracefully handle RTP sequence # rollover

### ISSUE THREAD

**Issue by haydenmc** [Glimesh/janus-ftl-plugin#95]

**Comment by danstiner** [comment]
My rough plan is to:
- Merge #122 so we can haveextended sequence numbers that do not rollover
- Extract the existing NACK code into a new class and add tests, maybe named PacketBuffer
- Enable NACKs behind a feature flag so it can be tested for as long as needed before fully rolling it out

**Comment by danstiner** [comment]
Will follow up with tests later as part of improving metrics.
